<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5c62cadbdf9b5',
    'title' => __('Mail', 'modularity-resource-booking'),
    'fields' => array(
        0 => array(
            'key' => 'field_5c62cae5bddaf',
            'label' => __('Recipient', 'modularity-resource-booking'),
            'name' => 'reciver',
            'type' => 'text',
            'instructions' => __('Use comma seperated list of emails (for multiple recipients). Avalible shortcodes for dynamic recipients: <b>[customer-mail] [manager-mail] [economy-mail]</b>', 'modularity-resource-booking'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        1 => array(
            'key' => 'field_5c62cb4746df9',
            'label' => __('Subject', 'modularity-resource-booking'),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        2 => array(
            'key' => 'field_5c62cb4e46dfa',
            'label' => __('Content', 'modularity-resource-booking'),
            'name' => 'content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
        ),
        3 => array(
            'key' => 'field_5c62fd7092a47',
            'label' => __('Link', 'modularity-resource-booking'),
            'name' => 'link',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        4 => array(
            'key' => 'field_5c62daa7cb089',
            'label' => __('Additional Content', 'modularity-resource-booking'),
            'name' => 'additional_content',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'customerDetails' => __('Customer Details', 'modularity-resource-booking'),
                'orderDetails' => __('Order Details', 'modularity-resource-booking'),
                'orderSummary' => __('Order Summary', 'modularity-resource-booking'),
            ),
            'allow_custom' => 0,
            'default_value' => array(
            ),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
            'save_custom' => 0,
        ),
        5 => array(
            'key' => 'field_5c6404dd0eba2',
            'label' => __('Customer details - Heading', 'modularity-resource-booking'),
            'name' => 'customer_details_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5c62daa7cb089',
                        'operator' => '==',
                        'value' => 'customerDetails',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        6 => array(
            'key' => 'field_5c6404f30eba3',
            'label' => __('Customer details - Fields', 'modularity-resource-booking'),
            'name' => 'customer_details_fields',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5c62daa7cb089',
                        'operator' => '==',
                        'value' => 'customerDetails',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'name' => __('Name', 'modularity-resource-booking'),
                'email' => __('Email', 'modularity-resource-booking'),
                'phone' => __('Phone', 'modularity-resource-booking'),
                'glnr' => __('GLNR', 'modularity-resource-booking'),
                'vat' => __('Vat Number', 'modularity-resource-booking'),
                'company' => __('Company', 'modularity-resource-booking'),
                'companyNumber' => __('Company Number', 'modularity-resource-booking'),
                'contactPerson' => __('Contact Person', 'modularity-resource-booking'),
                'billingAddress' => __('Billing Address', 'modularity-resource-booking'),
            ),
            'allow_custom' => 0,
            'default_value' => array(
                0 => __('name', 'modularity-resource-booking'),
                1 => __('email', 'modularity-resource-booking'),
                2 => __('phone', 'modularity-resource-booking'),
                3 => __('glnr', 'modularity-resource-booking'),
                4 => __('vat', 'modularity-resource-booking'),
                5 => __('company', 'modularity-resource-booking'),
                6 => __('companyNumber', 'modularity-resource-booking'),
                7 => __('contactPerson', 'modularity-resource-booking'),
                8 => __('billingAddress', 'modularity-resource-booking'),
            ),
            'layout' => 'vertical',
            'toggle' => 1,
            'return_format' => 'value',
            'save_custom' => 0,
        ),
        7 => array(
            'key' => 'field_5c64077a3b60b',
            'label' => __('Order details - Heading', 'modularity-resource-booking'),
            'name' => 'order_details_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5c62daa7cb089',
                        'operator' => '==',
                        'value' => 'orderDetails',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        8 => array(
            'key' => 'field_5c6407c13b60c',
            'label' => __('Order details - Fields', 'modularity-resource-booking'),
            'name' => 'order_details_fields',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5c62daa7cb089',
                        'operator' => '==',
                        'value' => 'orderDetails',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'orderId' => __('Order ID', 'modularity-resource-booking'),
                'orderDate' => __('Order date', 'modularity-resource-booking'),
                'campaignName' => __('Campaign name', 'modularity-resource-booking'),
            ),
            'allow_custom' => 0,
            'default_value' => array(
                0 => __('orderId', 'modularity-resource-booking'),
                1 => __('orderDate', 'modularity-resource-booking'),
                2 => __('campaignName', 'modularity-resource-booking'),
            ),
            'layout' => 'vertical',
            'toggle' => 1,
            'return_format' => 'value',
            'save_custom' => 0,
        ),
        9 => array(
            'key' => 'field_5c649828710e8',
            'label' => __('Order summary - Heading', 'modularity-resource-booking'),
            'name' => 'order_summary_heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5c62daa7cb089',
                        'operator' => '==',
                        'value' => 'orderSummary',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'modularity-rb-mail',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}